Change logo on projects page from MLH Fellowship to Prep
MLH-Fellowship/march-2022-prep-portfolio pull request #16
Opened 2022-03-08 14:10 UTC by chiuannica

## Please, go through these steps before you submit a PR.

- [ X ] My Pod Leader knows I'm working on this Pull Request
- [ X ] I've explained what the Pull Request is adding.
- [ X ] I've explained why this is important.

This pull request is changing the MLH Fellowship logo (svg) to the MLH Prep logo (png). This is important because the prep logo is used on the home page, and there should be consistency throughout the site.

I changed it by changing logo.svg to mlh-prep.png. Since they are different formats, the new logo needed to be resized to fit properly. I used the class "w-100" from Bootstrap to make the width 100% of the area and fit in above "Projects" properly.

Wide screen
![Screen Shot 2022-03-08 at 10 09 12 PM](https://user-images.githubusercontent.com/45278655/157254199-b0dc3bc6-245e-4d97-95e0-ecb06b1b119b.png)

Mid-size screen
<img width="1133" alt="Screen Shot 2022-03-08 at 9 54 03 PM" src="https://user-images.githubusercontent.com/45278655/157251585-e64ba207-9a71-4d49-879e-abf72fa05baf.png">

Narrow screen
<img width="612" alt="Screen Shot 2022-03-08 at 10 08 12 PM" src="https://user-images.githubusercontent.com/45278655/157254161-3547d223-9ff9-4a04-b8e5-69209d04b517.png">

2022-03-09 05:53 UTC, sohamsshah requested changes
Hey @chiuannica , great work 🥳.
Since you are working for the logo image, I have suggested a small enhancement. Would like to know your views on that!

2022-03-09 05:53 UTC, sohamsshah commented on _layouts/page.html
> +                <img class="w-100" src="/assets/img/mlh-prep.png"/>
Having `alt` attribute in the `img` tags would be great in terms of accessibility. Also, to have better [CLS](https://web.dev/cls/), it is a good practice to add `width` and `height` attributes to the images in the DOM.

2022-03-09 07:52 UTC, marcnjaramillo requested changes
This is an excellent start. Thank you for paying close attention to the appearance of the logo for different screen widths. I left one comment, and once you address that we'll be ready to merge.

2022-03-09 07:52 UTC, marcnjaramillo commented on _layouts/page.html
> +                <img class="w-100" src="/assets/img/mlh-prep.png"/>
@sohamsshah makes a good point about accessibility. Here is a good resource for [alt text](https://webaim.org/techniques/alttext/) and a well thought-out post on [StackOverflow](https://stackoverflow.com/questions/23526791/when-is-it-acceptable-to-leave-the-alt-text-empty-on-an-html-image-if-ever) if you would like to learn more about it. Note that the alt text doesn't need to be overly descriptive; something like "mlh prep program logo" would be sufficient.

2022-03-09 12:17 UTC, chiuannica commented on _layouts/page.html
> +                <img class="w-100" src="/assets/img/mlh-prep.png"/>
Thanks for the input, I overlooked that!

2022-03-09 12:21 UTC, sohamsshah commented on _layouts/page.html
> +                <img class="w-100" src="/assets/img/mlh-prep.png"/>
Awesome 🙌👍

2022-03-11 06:10 UTC, marcnjaramillo approved these changes
Great work!

2022-03-11 06:10 UTC, merged